teamorg/config/routes.rb
Teamorg::Application.routes.draw do
  resources :athletes_parents

  resources :athletes_rosters

  resources :rosters do
    get :details, :on => :member
  end

  resources :teams

  resources :athletes

  resources :people_phones

  resources :phones

  resources :emails_people

  resources :emails

  resources :addresses_people

  resources :addresses

  resources :people

end

teamorg/app/models/address.rb
class Address < ActiveRecord::Base
  has_and_belongs_to_many :people
  
  def address_types 
    {:home => 1, :work => 2, :other => 3}.freeze      
  end
  
  def to_s
    @addr = (self.line1 ? line1 : "") + (self.line2 ? line2 : "")
    @addr += (self.city || self.state || self.country || self.postal_code ? ", " : "")
    @addr += (self.city ? city : "") 
    @addr += (self.state ? (self.city ? ", " + state : state) : "")
    @addr += (self.country ? ", " : (self.postal_code ? " " : ""))    
    @addr += (self.country ? country : "") + (self.postal_code ? (self.country ? " " + postal_code : postal_code) : "")
  end
  
end

teamorg/app/models/addresses_person.rb
class AddressesPerson < ActiveRecord::Base
end

teamorg/app/models/athlete.rb
class Athlete < ActiveRecord::Base
  belongs_to  :person
  has_and_belongs_to_many :rosters
  has_and_belongs_to_many :parents, :join_table => "athletes_parents", :class_name => "Person", :table_name => "people"  
end

teamorg/app/models/athletes_parent.rb
class AthletesParent < ActiveRecord::Base
end

teamorg/app/models/athletes_roster.rb
class AthletesRoster < ActiveRecord::Base
end

teamorg/app/models/email.rb
class Email < ActiveRecord::Base
  has_and_belongs_to_many :people
  
  def email_types
    {:home => 1, :work => 2, :other => 3}.freeze
  end
  
  validates :address, :presence => true, 
                      :uniqueness => true, 
                      :email_format => true
            
end

teamorg/app/models/emails_person.rb
class EmailsPerson < ActiveRecord::Base
end

teamorg/app/models/people_phone.rb
class PeoplePhone < ActiveRecord::Base
end

teamorg/app/models/person.rb
class Person < ActiveRecord::Base
  has_and_belongs_to_many :addresses
  has_and_belongs_to_many :emails
  has_and_belongs_to_many :phones
  has_one :athlete
  has_and_belongs_to_many :athletes, :join_table => "athletes_parents"

  validate :last_name, :presence => true
  
  def sex_types
    {:male => 1, :female => 2}.freeze
  end 
    
  def full_name
    [self.first_name, self.last_name].compact.join(" ")
  end
  
  def add_address(address)
    self.addresses << address
  end
  
  def delete_address(address)
    refs = AddressesPerson.where(:address_id => address.id).length # how many people reference the address
    self.addresses.delete(address)  # always destory the join table record
    address.destroy if (refs == 1)  # if that was the only person referencing the address, destroy the address    
  end
  
  def add_email(email)
    if em = Email.where(["address = ?", email.address]).first   # is the email address already in the DB?
      if EmailsPerson.where(:person_id => self.id, :email_id => em.id).empty? # make sure person is not already related to email address -- if so, ignore this request
        begin 
          EmailsPerson.new(:person_id => self.id, :email_id => em.id).save! 
        rescue RecordInvalid => error
          # EmailsPerson record could not be saved
        end
      end
    else
      begin 
        self.emails << email
      rescue RecordInvalid => error
        # Email record could not be saved
      end
    end
  end
  
  def delete_email(email)
    refs = EmailsPerson.where(:email_id => email.id).length # how many people reference the phone
    self.emails.delete(email)  # always destory the join table record
    email.destroy if (refs == 1)  # if that was the only person referencing the phone, destroy the phone
  end
  
  def add_phone(phone)   
    if ph = Phone.where(["number = ?", phone.number]).first   # is the phone number already in the DB?
      if PeoplePhone.where(:person_id => self.id, :phone_id => ph.id).empty? # make sure person is not already related to phone number -- if so, ignore this request
        begin 
          PeoplePhone.new(:person_id => self.id, :phone_id => ph.id).save! 
        rescue RecordInvalid => error
          # PeoplePhone record could not be saved
        end
      end
    else
      begin 
        self.phones << phone
      rescue RecordInvalid => error
        # Phone record could not be saved
      end
    end
  end
  
  def delete_phone(phone)
    refs = PeoplePhone.where(:phone_id => phone.id).length # how many people reference the phone
    self.phones.delete(phone)  # always destory the join table record
    phone.destroy if (refs == 1)  # if that was the only person referencing the phone, destroy the phone
  end
  
end

teamorg/app/models/phone.rb
class Phone < ActiveRecord::Base
  before_validation :scrub_number
    
  has_and_belongs_to_many :people

  def phone_types
    {:home => 1, :work => 2, :mobile => 3, :fax => 4, :other => 5}.freeze
  end 

  validates :number,  :presence => true,
                      :uniqueness => true,
                      :length => {:minimum =>10, :maximum => 10}
  
  private
  
  def scrub_number
    self.number.gsub!(/[^0-9]/, "") if attribute_present?("number")
  end
  
end

teamorg/app/models/roster.rb
class Roster < ActiveRecord::Base
  belongs_to :team
  has_and_belongs_to_many :athletes
end

teamorg/app/models/team.rb
class Team < ActiveRecord::Base
  has_many :rosters
  has_and_belongs_to_many :coaches
end

teamorg/app/controllers/athletes_rosters_controller.rb
class AthletesRostersController < ApplicationController
  # GET /athletes_rosters
  # GET /athletes_rosters.xml
  def index
    @athletes_rosters = AthletesRoster.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @athletes_rosters }
    end
  end

  # GET /athletes_rosters/1
  # GET /athletes_rosters/1.xml
  def show
    @athletes_roster = AthletesRoster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @athletes_roster }
    end
  end

  # GET /athletes_rosters/new
  # GET /athletes_rosters/new.xml
  def new
    @athletes_roster = AthletesRoster.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @athletes_roster }
    end
  end

  # GET /athletes_rosters/1/edit
  def edit
    @athletes_roster = AthletesRoster.find(params[:id])
  end

  # POST /athletes_rosters
  # POST /athletes_rosters.xml
  def create
    @athletes_roster = AthletesRoster.new(params[:athletes_roster])

    respond_to do |format|
      if @athletes_roster.save
        format.html { redirect_to(@athletes_roster, :notice => 'Athletes roster was successfully created.') }
        format.xml  { render :xml => @athletes_roster, :status => :created, :location => @athletes_roster }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @athletes_roster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /athletes_rosters/1
  # PUT /athletes_rosters/1.xml
  def update
    @athletes_roster = AthletesRoster.find(params[:id])

    respond_to do |format|
      if @athletes_roster.update_attributes(params[:athletes_roster])
        format.html { redirect_to(@athletes_roster, :notice => 'Athletes roster was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @athletes_roster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes_rosters/1
  # DELETE /athletes_rosters/1.xml
  def destroy
    @athletes_roster = AthletesRoster.find(params[:id])
    @athletes_roster.destroy

    respond_to do |format|
      format.html { redirect_to(athletes_rosters_url) }
      format.xml  { head :ok }
    end
  end
end

teamorg/app/helpers/addresses_helper.rb
module AddressesHelper
end

teamorg/app/helpers/application_helper.rb
module ApplicationHelper
end

teamorg/app/helpers/athletes_helper.rb
module AthletesHelper
end

teamorg/app/helpers/athletes_rosters_helper.rb
module AthletesRostersHelper
end

teamorg/app/helpers/contacts_helper.rb
module ContactsHelper
end

teamorg/app/helpers/emails_helper.rb
module EmailsHelper
end

teamorg/app/helpers/people_helper.rb
module PeopleHelper
end

teamorg/app/helpers/phones_helper.rb
module PhonesHelper
end

teamorg/app/helpers/rosters_helper.rb
module RostersHelper
end

teamorg/app/helpers/teams_helper.rb
module TeamsHelper
end

teamorg/app/views/athletes_rosters/_form.html.erb
<%= form_for(@athletes_roster) do |f| %>
  <% if @athletes_roster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@athletes_roster.errors.count, "error") %> prohibited this athletes_roster from being saved:</h2>

      <ul>
      <% @athletes_roster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :athlete_id %><br />
    <%= f.text_field :athlete_id %>
  </div>
  <div class="field">
    <%= f.label :roster_id %><br />
    <%= f.text_field :roster_id %>
  </div>
  <div class="field">
    <%= f.label :jersey_number %><br />
    <%= f.text_field :jersey_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

teamorg/app/views/athletes_rosters/edit.html.erb
<h1>Editing athletes_roster</h1>

<%= render 'form' %>

<%= link_to 'Show', @athletes_roster %> |
<%= link_to 'Back', athletes_rosters_path %>

teamorg/app/views/athletes_rosters/index.html.erb
<h1>Listing athletes_rosters</h1>

<table>
  <tr>
    <th>Athlete</th>
    <th>Roster</th>
    <th>Jersey number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @athletes_rosters.each do |athletes_roster| %>
  <tr>
    <td><%= athletes_roster.athlete_id %></td>
    <td><%= athletes_roster.roster_id %></td>
    <td><%= athletes_roster.jersey_number %></td>
    <td><%= link_to 'Show', athletes_roster %></td>
    <td><%= link_to 'Edit', edit_athletes_roster_path(athletes_roster) %></td>
    <td><%= link_to 'Destroy', athletes_roster, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Athletes roster', new_athletes_roster_path %>

teamorg/app/views/athletes_rosters/new.html.erb
<h1>New athletes_roster</h1>

<%= render 'form' %>

<%= link_to 'Back', athletes_rosters_path %>

teamorg/app/views/athletes_rosters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Athlete:</b>
  <%= @athletes_roster.athlete_id %>
</p>

<p>
  <b>Roster:</b>
  <%= @athletes_roster.roster_id %>
</p>

<p>
  <b>Jersey number:</b>
  <%= @athletes_roster.jersey_number %>
</p>


<%= link_to 'Edit', edit_athletes_roster_path(@athletes_roster) %> |
<%= link_to 'Back', athletes_rosters_path %>