teamorg/config/routes.rb
Teamorg::Application.routes.draw do
  resources :athletes_parents

  resources :athletes_rosters

  resources :rosters do
    get :details, :on => :member
  end

  resources :teams

  resources :athletes

  resources :people_phones

  resources :phones

  resources :emails_people

  resources :emails

  resources :addresses_people

  resources :addresses

  resources :people

end

teamorg/app/models/roster.rb
class Roster < ActiveRecord::Base
  belongs_to :team
  has_and_belongs_to_many :athletes
end

teamorg/app/controllers/rosters_controller.rb
class RostersController < ApplicationController
  # GET /rosters
  # GET /rosters.xml
  def index
    @rosters = Roster.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rosters }
    end
  end

  # GET /rosters/1
  # GET /rosters/1.xml
  def show
    @roster = Roster.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @roster } # this needs to be fixed!!
    end
  end
  
  # GET /rosters/1/details/
  def details
    @roster = Roster.find(params[:id])

    respond_to do |format|
      format.html # details.html.erb
#      format.xml  { render :xml => @roster } # this needs to be fixed!!
    end
  end

  # GET /rosters/new
  # GET /rosters/new.xml
  def new
    @roster = Roster.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @roster }
    end
  end

  # GET /rosters/1/edit
  def edit
    @roster = Roster.find(params[:id])
  end

  # POST /rosters
  # POST /rosters.xml
  def create
    @roster = Roster.new(params[:roster])

    respond_to do |format|
      if @roster.save
        format.html { redirect_to(@roster, :notice => 'Roster was successfully created.') }
        format.xml  { render :xml => @roster, :status => :created, :location => @roster }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @roster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rosters/1
  # PUT /rosters/1.xml
  def update
    @roster = Roster.find(params[:id])

    respond_to do |format|
      if @roster.update_attributes(params[:roster])
        format.html { redirect_to(@roster, :notice => 'Roster was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @roster.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /rosters/1
  # DELETE /rosters/1.xml
  def destroy
    @roster = Roster.find(params[:id])
    @roster.destroy

    respond_to do |format|
      format.html { redirect_to(rosters_url) }
      format.xml  { head :ok }
    end
  end
end

teamorg/app/helpers/rosters_helper.rb
module RostersHelper
end

teamorg/app/views/rosters/_form.html.erb
<%= form_for(@roster) do |f| %>
  <% if @roster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@roster.errors.count, "error") %> prohibited this roster from being saved:</h2>

      <ul>
      <% @roster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br />
    <%= f.text_field :team_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

teamorg/app/views/rosters/details.html.erb
<h1><%=h @roster.team.name %> - <%=h @roster.name %></h1>

<table>
  <tr>
	<th>#</th>
    <th>Name</th>	
	<th>DOB</th>
    <th>Address</th>
	<th>Phone</th>
	<th>Email</th>
  </tr>

<% @roster.athletes.each do |athlete| %>
  <tr>
    <td><%=h athlete.jersey_number %></td>
    <td><b><%=h athlete.person.full_name %></b></td>
	<td><%=h athlete.person.date_of_birth %></td>
	<td>
		<% num_addresses = athlete.person.addresses.length %>
		<% athlete.person.addresses.each_with_index do |address,i| %>
			<%=h address.to_s %>
			<%=h ", " if i != num_addresses-1 %>
		<% end %>
	</td>
	<td>
		<% num_phones = athlete.person.phones.length %>
		<% athlete.person.phones.each_with_index do |phone,i| %>
			<%=h number_to_phone(phone.number, :area_code => true) %>
			<%=h "[" + phone.phone_types.key(phone.phone_type).to_s + "]" if phone.phone_type %>
			<%=h ", " if i != num_phones-1 %>
		<% end %>
	</td>
	<td>
		<% num_emails = athlete.person.emails.length %>
		<% athlete.person.emails.each_with_index do |email,i| %>
			<%=h email.address %>
			<%=h ", " if i != num_emails-1 %>
		<% end %>
	</td>
  </tr>
  <% athlete.parents.each do |parent| %>
    <tr>
	  <td></td>
	  <td>&nbsp;&nbsp;<%=h p parent.full_name %></td>
	  <td></td>	
	  <td>
		<% num_addresses = parent.addresses.length %>
		<% parent.addresses.each_with_index do |address,i| %>
			<%=h address.to_s %>
			<%=h ", " if i != num_addresses-1 %>
		<% end %>
	</td>
	<td>
		<% num_phones = parent.phones.length %>
		<% parent.phones.each_with_index do |phone,i| %>
			<%=h number_to_phone(phone.number, :area_code => true)%>
			<%=h ", " if i != num_phones-1 %>
		<% end %>
	</td>
	<td>
		<% num_emails = parent.emails.length %>
		<% parent.emails.each_with_index do |email,i| %>
			<%=h email.address %>
			<%=h ", " if i != num_emails-1 %>
		<% end %>
	</td>
    </tr>
  <% end %>
<% end %>
</table>

<br />

teamorg/app/views/rosters/edit.html.erb
<h1>Editing roster</h1>

<%= render 'form' %>

<%= link_to 'Show', @roster %> |
<%= link_to 'Back', rosters_path %>

teamorg/app/views/rosters/index.html.erb
<h1>Listing Rosters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rosters.each do |roster| %>
  <tr>
    <td><%= roster.name %></td>
    <td><%= roster.team_id %></td>
    <td><%= link_to 'Show', roster %></td>
    <td><%= link_to 'Edit', edit_roster_path(roster) %></td>
    <td><%= link_to 'Destroy', roster, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Roster', new_roster_path %>

teamorg/app/views/rosters/new.html.erb
<h1>New roster</h1>

<%= render 'form' %>

<%= link_to 'Back', rosters_path %>

teamorg/app/views/rosters/show.html.erb
<h1><%= @roster.team.name %></h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Roster:</b>
  <%= @roster.name %>
</p>

<p>
<table>
  <tr>
    <th>#</th>
    <th>Athlete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @roster.athletes.each do |athlete| %>
  <tr>
    <td><%=h athlete.jersey_number %></td>
    <td><%=h athlete.person.full_name %></td>
    <td><%= link_to 'Show', athlete %></td>
    <td><%= link_to 'Edit', edit_athlete_path(athlete) %></td>
    <td><%= link_to 'Destroy', athlete, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</p>

<%= link_to 'Edit', edit_roster_path(@roster) %> |
<%= link_to 'Back', rosters_path %>