teamorg/config/routes.rb
Teamorg::Application.routes.draw do
  resources :athletes_parents

  resources :athletes_rosters

  resources :rosters do
    get :details, :on => :member
  end

  resources :teams

  resources :athletes

  resources :people_phones

  resources :phones

  resources :emails_people

  resources :emails

  resources :addresses_people

  resources :addresses

  resources :people

end

teamorg/app/models/athlete.rb
class Athlete < ActiveRecord::Base
  belongs_to  :person
  has_and_belongs_to_many :rosters
  has_and_belongs_to_many :parents, :join_table => "athletes_parents", :class_name => "Person", :table_name => "people"  
end

teamorg/app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  # GET /athletes
  # GET /athletes.xml
  def index
    @athletes = Athlete.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @athletes }
    end
  end

  # GET /athletes/1
  # GET /athletes/1.xml
  def show
    @athlete = Athlete.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @athlete }
    end
  end

  # GET /athletes/new
  # GET /athletes/new.xml
  def new
    @athlete = Athlete.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @athlete }
    end
  end

  # GET /athletes/1/edit
  def edit
    @athlete = Athlete.find(params[:id])
  end

  # POST /athletes
  # POST /athletes.xml
  def create
    @athlete = Athlete.new(params[:athlete])

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to(@athlete, :notice => 'Athlete was successfully created.') }
        format.xml  { render :xml => @athlete, :status => :created, :location => @athlete }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @athlete.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /athletes/1
  # PUT /athletes/1.xml
  def update
    @athlete = Athlete.find(params[:id])

    respond_to do |format|
      if @athlete.update_attributes(params[:athlete])
        format.html { redirect_to(@athlete, :notice => 'Athlete was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @athlete.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.xml
  def destroy
    @athlete = Athlete.find(params[:id])
    @athlete.destroy

    respond_to do |format|
      format.html { redirect_to(athletes_url) }
      format.xml  { head :ok }
    end
  end
end

teamorg/app/helpers/athletes_helper.rb
module AthletesHelper
end

teamorg/app/views/athletes/_form.html.erb
<%= form_for(@athlete) do |f| %>
  <% if @athlete.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@athlete.errors.count, "error") %> prohibited this athlete from being saved:</h2>

      <ul>
      <% @athlete.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :person_id %><br />
    <%= f.text_field :person_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

teamorg/app/views/athletes/edit.html.erb
<h1>Editing athlete</h1>

<%= render 'form' %>

<%= link_to 'Show', @athlete %> |
<%= link_to 'Back', athletes_path %>

teamorg/app/views/athletes/index.html.erb
<h1>Listing Athletes</h1>

<table>
  <tr>
    <th>Athlete</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @athletes.each do |athlete| %>
  <tr>
    <td><%= athlete.person.full_name %></td>
    <td><%= link_to 'Show', athlete %></td>
    <td><%= link_to 'Edit', edit_athlete_path(athlete) %></td>
    <td><%= link_to 'Destroy', athlete, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Athlete', new_athlete_path %>

teamorg/app/views/athletes/new.html.erb
<h1>New athlete</h1>

<%= render 'form' %>

<%= link_to 'Back', athletes_path %>

teamorg/app/views/athletes/show.html.erb
<h1>Athlete Information:</h1>
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @athlete.person.full_name %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @athlete.person.date_of_birth %>
</p>

<p>
  <b>Sex:</b>
  <%= @athlete.person.sex_types.key(@athlete.person.sex) %>
</p>

<% unless @athlete.parents.empty? %>
  <p>
  <table>
    <tr>
      <th>Parent/Guardian</th>
    </tr>

    <% @athlete.parents.each do |parent| %>
      <tr>
        <td><%= parent.full_name %></td>
      </tr>
    <% end %>
  </table>
  </p>
<% end %>

<h2>Contact Information:</h2>

<p>
<table>
  <tr>
    <th>Address</th>
  </tr>

  <% @athlete.person.addresses.each do |address| %>
    <tr>
      <td><%= address.to_s %>
	      (<%= address.address_types.key(address.address_type) if address.address_type %>)</td>
    </tr>
  <% end %>
</table>
</p>

<p>
<table>
  <tr>
    <th>Phone</th>
  </tr>

  <% @athlete.person.phones.each do |phone| %>
    <tr>
      <td><%= number_to_phone(phone.number, :area_code => true) %>     	
	      (<%= phone.phone_types.key(phone.phone_type) if phone.phone_type %>)</td>
    </tr>
  <% end %>
</table>
</p>

<p>
<table>
  <tr>
    <th>Email</th>
  </tr>

  <% @athlete.person.emails.each do |email| %>
    <tr>
      <td><%= email.address %>
		  (<%= email.email_types.key(email.email_type) if email.email_type %>)</td>
    </tr>
  <% end %>
</table>
</p>

<%= link_to 'Edit', edit_athlete_path(@athlete) %> |
<%= link_to 'Back', athletes_path %>